/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FrameworkPackageRouteImport } from './routes/framework-package'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesNewRouteImport } from './routes/cases.new'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as CasesCaseIdIndexRouteImport } from './routes/cases.$caseId.index'
import { Route as CasesCaseIdSourcesRouteImport } from './routes/cases.$caseId.sources'
import { Route as CasesCaseIdScopeRouteImport } from './routes/cases.$caseId.scope'
import { Route as CasesCaseIdReviewRouteImport } from './routes/cases.$caseId.review'
import { Route as CasesCaseIdReportRouteImport } from './routes/cases.$caseId.report'
import { Route as CasesCaseIdIngestionRouteImport } from './routes/cases.$caseId.ingestion'
import { Route as CasesCaseIdExtractionRouteImport } from './routes/cases.$caseId.extraction'
import { Route as ApiHimamExtractEvidenceRouteImport } from './routes/api.himam.extract-evidence'

const FrameworkPackageRoute = FrameworkPackageRouteImport.update({
  id: '/framework-package',
  path: '/framework-package',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const CasesNewRoute = CasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCaseIdIndexRoute = CasesCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdSourcesRoute = CasesCaseIdSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdScopeRoute = CasesCaseIdScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdReviewRoute = CasesCaseIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdReportRoute = CasesCaseIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdIngestionRoute = CasesCaseIdIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdExtractionRoute = CasesCaseIdExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const ApiHimamExtractEvidenceRoute = ApiHimamExtractEvidenceRouteImport.update({
  id: '/api/himam/extract-evidence',
  path: '/api/himam/extract-evidence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/framework-package': typeof FrameworkPackageRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
  '/api/himam/extract-evidence': typeof ApiHimamExtractEvidenceRoute
  '/cases/$caseId/extraction': typeof CasesCaseIdExtractionRoute
  '/cases/$caseId/ingestion': typeof CasesCaseIdIngestionRoute
  '/cases/$caseId/report': typeof CasesCaseIdReportRoute
  '/cases/$caseId/review': typeof CasesCaseIdReviewRoute
  '/cases/$caseId/scope': typeof CasesCaseIdScopeRoute
  '/cases/$caseId/sources': typeof CasesCaseIdSourcesRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/framework-package': typeof FrameworkPackageRoute
  '/cases/new': typeof CasesNewRoute
  '/cases': typeof CasesIndexRoute
  '/api/himam/extract-evidence': typeof ApiHimamExtractEvidenceRoute
  '/cases/$caseId/extraction': typeof CasesCaseIdExtractionRoute
  '/cases/$caseId/ingestion': typeof CasesCaseIdIngestionRoute
  '/cases/$caseId/report': typeof CasesCaseIdReportRoute
  '/cases/$caseId/review': typeof CasesCaseIdReviewRoute
  '/cases/$caseId/scope': typeof CasesCaseIdScopeRoute
  '/cases/$caseId/sources': typeof CasesCaseIdSourcesRoute
  '/cases/$caseId': typeof CasesCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/framework-package': typeof FrameworkPackageRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
  '/api/himam/extract-evidence': typeof ApiHimamExtractEvidenceRoute
  '/cases/$caseId/extraction': typeof CasesCaseIdExtractionRoute
  '/cases/$caseId/ingestion': typeof CasesCaseIdIngestionRoute
  '/cases/$caseId/report': typeof CasesCaseIdReportRoute
  '/cases/$caseId/review': typeof CasesCaseIdReviewRoute
  '/cases/$caseId/scope': typeof CasesCaseIdScopeRoute
  '/cases/$caseId/sources': typeof CasesCaseIdSourcesRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/framework-package'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases/'
    | '/api/himam/extract-evidence'
    | '/cases/$caseId/extraction'
    | '/cases/$caseId/ingestion'
    | '/cases/$caseId/report'
    | '/cases/$caseId/review'
    | '/cases/$caseId/scope'
    | '/cases/$caseId/sources'
    | '/cases/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/framework-package'
    | '/cases/new'
    | '/cases'
    | '/api/himam/extract-evidence'
    | '/cases/$caseId/extraction'
    | '/cases/$caseId/ingestion'
    | '/cases/$caseId/report'
    | '/cases/$caseId/review'
    | '/cases/$caseId/scope'
    | '/cases/$caseId/sources'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/framework-package'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases/'
    | '/api/himam/extract-evidence'
    | '/cases/$caseId/extraction'
    | '/cases/$caseId/ingestion'
    | '/cases/$caseId/report'
    | '/cases/$caseId/review'
    | '/cases/$caseId/scope'
    | '/cases/$caseId/sources'
    | '/cases/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  FrameworkPackageRoute: typeof FrameworkPackageRoute
  ApiHimamExtractEvidenceRoute: typeof ApiHimamExtractEvidenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/framework-package': {
      id: '/framework-package'
      path: '/framework-package'
      fullPath: '/framework-package'
      preLoaderRoute: typeof FrameworkPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/new': {
      id: '/cases/new'
      path: '/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof CasesNewRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$caseId/': {
      id: '/cases/$caseId/'
      path: '/'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof CasesCaseIdIndexRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/sources': {
      id: '/cases/$caseId/sources'
      path: '/sources'
      fullPath: '/cases/$caseId/sources'
      preLoaderRoute: typeof CasesCaseIdSourcesRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/scope': {
      id: '/cases/$caseId/scope'
      path: '/scope'
      fullPath: '/cases/$caseId/scope'
      preLoaderRoute: typeof CasesCaseIdScopeRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/review': {
      id: '/cases/$caseId/review'
      path: '/review'
      fullPath: '/cases/$caseId/review'
      preLoaderRoute: typeof CasesCaseIdReviewRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/report': {
      id: '/cases/$caseId/report'
      path: '/report'
      fullPath: '/cases/$caseId/report'
      preLoaderRoute: typeof CasesCaseIdReportRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/ingestion': {
      id: '/cases/$caseId/ingestion'
      path: '/ingestion'
      fullPath: '/cases/$caseId/ingestion'
      preLoaderRoute: typeof CasesCaseIdIngestionRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/extraction': {
      id: '/cases/$caseId/extraction'
      path: '/extraction'
      fullPath: '/cases/$caseId/extraction'
      preLoaderRoute: typeof CasesCaseIdExtractionRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/api/himam/extract-evidence': {
      id: '/api/himam/extract-evidence'
      path: '/api/himam/extract-evidence'
      fullPath: '/api/himam/extract-evidence'
      preLoaderRoute: typeof ApiHimamExtractEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CasesCaseIdRouteChildren {
  CasesCaseIdExtractionRoute: typeof CasesCaseIdExtractionRoute
  CasesCaseIdIngestionRoute: typeof CasesCaseIdIngestionRoute
  CasesCaseIdReportRoute: typeof CasesCaseIdReportRoute
  CasesCaseIdReviewRoute: typeof CasesCaseIdReviewRoute
  CasesCaseIdScopeRoute: typeof CasesCaseIdScopeRoute
  CasesCaseIdSourcesRoute: typeof CasesCaseIdSourcesRoute
  CasesCaseIdIndexRoute: typeof CasesCaseIdIndexRoute
}

const CasesCaseIdRouteChildren: CasesCaseIdRouteChildren = {
  CasesCaseIdExtractionRoute: CasesCaseIdExtractionRoute,
  CasesCaseIdIngestionRoute: CasesCaseIdIngestionRoute,
  CasesCaseIdReportRoute: CasesCaseIdReportRoute,
  CasesCaseIdReviewRoute: CasesCaseIdReviewRoute,
  CasesCaseIdScopeRoute: CasesCaseIdScopeRoute,
  CasesCaseIdSourcesRoute: CasesCaseIdSourcesRoute,
  CasesCaseIdIndexRoute: CasesCaseIdIndexRoute,
}

const CasesCaseIdRouteWithChildren = CasesCaseIdRoute._addFileChildren(
  CasesCaseIdRouteChildren,
)

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRouteWithChildren
  CasesNewRoute: typeof CasesNewRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRouteWithChildren,
  CasesNewRoute: CasesNewRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  FrameworkPackageRoute: FrameworkPackageRoute,
  ApiHimamExtractEvidenceRoute: ApiHimamExtractEvidenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
