/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesNewRouteImport } from './routes/cases.new'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as CasesCaseIdSourcesRouteImport } from './routes/cases.$caseId.sources'
import { Route as ApiHimamExtractEvidenceRouteImport } from './routes/api.himam.extract-evidence'

const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const CasesNewRoute = CasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCaseIdSourcesRoute = CasesCaseIdSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const ApiHimamExtractEvidenceRoute = ApiHimamExtractEvidenceRouteImport.update({
  id: '/api/himam/extract-evidence',
  path: '/api/himam/extract-evidence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
  '/api/himam/extract-evidence': typeof ApiHimamExtractEvidenceRoute
  '/cases/$caseId/sources': typeof CasesCaseIdSourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/new': typeof CasesNewRoute
  '/cases': typeof CasesIndexRoute
  '/api/himam/extract-evidence': typeof ApiHimamExtractEvidenceRoute
  '/cases/$caseId/sources': typeof CasesCaseIdSourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
  '/api/himam/extract-evidence': typeof ApiHimamExtractEvidenceRoute
  '/cases/$caseId/sources': typeof CasesCaseIdSourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases/'
    | '/api/himam/extract-evidence'
    | '/cases/$caseId/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases'
    | '/api/himam/extract-evidence'
    | '/cases/$caseId/sources'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases/'
    | '/api/himam/extract-evidence'
    | '/cases/$caseId/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  ApiHimamExtractEvidenceRoute: typeof ApiHimamExtractEvidenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/new': {
      id: '/cases/new'
      path: '/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof CasesNewRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$caseId/sources': {
      id: '/cases/$caseId/sources'
      path: '/sources'
      fullPath: '/cases/$caseId/sources'
      preLoaderRoute: typeof CasesCaseIdSourcesRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/api/himam/extract-evidence': {
      id: '/api/himam/extract-evidence'
      path: '/api/himam/extract-evidence'
      fullPath: '/api/himam/extract-evidence'
      preLoaderRoute: typeof ApiHimamExtractEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CasesCaseIdRouteChildren {
  CasesCaseIdSourcesRoute: typeof CasesCaseIdSourcesRoute
}

const CasesCaseIdRouteChildren: CasesCaseIdRouteChildren = {
  CasesCaseIdSourcesRoute: CasesCaseIdSourcesRoute,
}

const CasesCaseIdRouteWithChildren = CasesCaseIdRoute._addFileChildren(
  CasesCaseIdRouteChildren,
)

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRouteWithChildren
  CasesNewRoute: typeof CasesNewRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRouteWithChildren,
  CasesNewRoute: CasesNewRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  ApiHimamExtractEvidenceRoute: ApiHimamExtractEvidenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
